---


- hosts: web:db
  become: yes
  vars:
    http_port: 85
    doc_root: /var/www/html/payment-gw
    doc_dir: /ansible/


  vars_prompt: 
  - name: sitename
    prompt: What would be your site name ? 

  tasks:
  - name: Install HTTPD Packages
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start HTTPD Service
    service: name=httpd state=started enabled=True
    when: ansible_os_family == "RedHat"

  - name: Install Apache Packages
    apt: name=apache2 state=present

  - name: Start Apache Service
    service: name=apache2 state=started enabled=True

  - name: Deploy Apache Server Configuration
    template: src=templates/apache2.j2 dest=/etc/apache2/apache2.conf
    notify:
      - Restart Apache
      - amit

  - name: Meta Force to Flush Handlres
    meta: flush_handlers


  - name: Create Site Location
    file: path={{doc_root}} state=directory


  - name: Deploy Sample Configuration
    copy: src=files/sample.html dest={{doc_root}}/index.html
    notify:
      - Restart Apache

  - name: Deploy Sample Configuration Template
    template: src=templates/sample.j2 dest={{doc_root}}/sample.html

  - name: Deploy Sample Configuration Template
    template: src=templates/info.j2 dest={{doc_root}}/info.html


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted
  - name: amit
    shell: 'echo "Hello Handlers" > /tmp/abc.html'

- hosts: db
  become: yes 

  tasks:
  - name: Install MariaDB Packages
    apt: name=mariadb-server state=present

- hosts: db:web
  become: yes 

  tasks:
  - name: Stop the Firewall
    service: name=ufw state=stopped

